CREATE TABLE `hnoms_bb_user` (
  `id` varchar(32) NOT NULL,
  `oa_id` varchar(32) DEFAULT NULL COMMENT 'oa用户id',
  `user_code` varchar(32) DEFAULT NULL COMMENT 'user_code',
  `name` varchar(32) DEFAULT NULL COMMENT '姓名',
  `telephone` varchar(32) DEFAULT NULL COMMENT '移动电话',
  `email` varchar(32) DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(32) DEFAULT NULL COMMENT '电话',
  `job_title` varchar(128) DEFAULT NULL COMMENT '职位',
  `memo` varchar(64) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `is_del` int(11) DEFAULT '0' COMMENT '是否删除0 否 1 是',
  `version` int(11) DEFAULT '0' COMMENT '版本号',
  `oa_depart_id` bigint(20) DEFAULT NULL COMMENT 'oa部门id',
  `oa_depart_name` varchar(64) DEFAULT NULL COMMENT 'oa部门名称',
  `del_flag` varchar(8) DEFAULT NULL COMMENT 'oa用户状态',
  `accounttype` varchar(32) DEFAULT NULL COMMENT 'oa账户类型',
  PRIMARY KEY (`id`),
  UNIQUE KEY `hnoms_bb_user_user_code_uindex` (`user_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `hnoms_bb_coal_detail` (
  `id` varchar(32) NOT NULL,
  `coal_type_id` varchar(32) DEFAULT NULL COMMENT '煤种类型ID',
  `coal_code` varchar(32) DEFAULT NULL COMMENT '煤种编码',
  `sap_full_name` varchar(128) DEFAULT NULL COMMENT 'SAP全称',
  `short_name` varchar(32) DEFAULT NULL COMMENT '简称',
  `heating_value` varchar(32) DEFAULT NULL COMMENT '热值',
  `water` varchar(32) DEFAULT NULL COMMENT '水',
  `gray` varchar(32) DEFAULT NULL COMMENT '灰',
  `gray_melting_point` varchar(32) DEFAULT NULL COMMENT '灰熔点',
  `sulfur` varchar(32) DEFAULT NULL COMMENT '硫',
  `volatil` varchar(32) DEFAULT NULL COMMENT '挥',
  `create_by` varchar(32) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(32) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `version` int(11) DEFAULT '0',
  `is_del` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `hnoms_bb_coal_detail_id_uindex` (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='煤炭详情';

CREATE TABLE `hnoms_sale_opportunitats` (
  `id` varchar(32) NOT NULL,
  `opportunitats_code` varchar(32) DEFAULT NULL COMMENT '销售商机号',
  `department_id` varchar(32) DEFAULT NULL COMMENT '部门',
  `coal_id` varchar(64) DEFAULT NULL COMMENT '煤种详情',
  `heating_value` varchar(32) DEFAULT NULL COMMENT '热值',
  `water` varchar(32) DEFAULT NULL,
  `gray` varchar(32) DEFAULT NULL,
  `sulfur` varchar(32) DEFAULT NULL COMMENT '硫',
  `quantity` int(8) DEFAULT NULL COMMENT '数量(吨)',
  `delivery_time` datetime DEFAULT NULL COMMENT '交货时间',
  `validity_period` datetime DEFAULT NULL COMMENT '有效期',
  `received_cust` varchar(32) DEFAULT NULL COMMENT '收方客户',
  `prize_punish` text COMMENT '质量奖罚',
  `other` text,
  `status` varchar(8) DEFAULT NULL COMMENT '1待匹配 2匹配中 3已完成 4人工关闭 5已失效',
  `create_by` varchar(32) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(32) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `version` int(11) DEFAULT NULL,
  `surplus` int(8) DEFAULT NULL COMMENT '剩余数量',
  `lock_num` int(8) DEFAULT NULL COMMENT '锁定数量',
  `is_del` int(11) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `is_arised` int(1) NOT NULL DEFAULT '1' COMMENT '是否可以发起内约 0否 1是',
  `is_sms` int(1) NOT NULL DEFAULT '0' COMMENT '是否发送过短信 0否 1是',
  `price` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hnoms_sale_opportunitats_id_uindex` (`id`) USING BTREE,
  UNIQUE KEY `hnoms_sale_opportunitats_opportunitats_code_uindex` (`opportunitats_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='销售商机';



